"""Agent orchestration: the manual tool-calling loop.

Flow per request:
1. Validate + guardrail-check the user message.
2. Ask the LLM for either a tool call or a final answer. Tools can come
   from MCP servers (Travel, Safety) or local tools (e.g. RAG retrieval) —
   the LLM sees one flat list and doesn't know or care which.
3. If a tool call: validate its arguments against the tool's JSON schema,
   invoke it (via the MCP client or the local registry), and feed the
   result back in.
4. Repeat up to max_tool_iterations, then force a final plain-text answer —
   this caps how many tool calls a single request can trigger.
5. Deterministically attach a safety disclaimer when the topic warrants it.
   The disclaimer text itself is never generated by the LLM.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field

import structlog

from app.agent.guardrails import (
    SAFETY_DISCLAIMER,
    GuardrailViolation,
    looks_like_prompt_injection,
    mentions_safety_topic,
    validate_session_id,
    validate_tool_arguments,
    validate_user_message,
)
from app.agent.llm_client import ChatMessage, HuggingFaceLLMClient, LLMError
from app.agent.mcp_client import McpClientManager
from app.agent.prompts import build_system_prompt
from app.agent.tools import LocalToolRegistry
from app.config import get_settings

logger = structlog.get_logger(__name__)


@dataclass
class ToolInvocation:
    name: str
    arguments: dict
    result: str | None = None
    error: str | None = None


@dataclass
class AgentResult:
    reply: str
    tool_calls: list[ToolInvocation] = field(default_factory=list)
    disclaimer: str | None = None
    flagged_injection: bool = False


class AgentOrchestrator:
    def __init__(
        self,
        llm_client: HuggingFaceLLMClient,
        mcp_manager: McpClientManager,
        local_tools: LocalToolRegistry | None = None,
    ) -> None:
        self._llm = llm_client
        self._mcp = mcp_manager
        self._local = local_tools or LocalToolRegistry()
        self._settings = get_settings()

    async def handle_message(
        self,
        user_message: str,
        session_id: str | None = None,
        max_iterations: int | None = None,
        max_tokens: int | None = None,
    ) -> AgentResult:
        clean_message = validate_user_message(user_message, self._settings.max_message_length)
        clean_session_id = validate_session_id(session_id)
        flagged = looks_like_prompt_injection(clean_message)
        if flagged:
            logger.warning("possible_prompt_injection", message_preview=clean_message[:80])

        tools = self._mcp.list_tools() + self._local.list_tools()
        messages = [
            ChatMessage(role="system", content=build_system_prompt(tools)),
            ChatMessage(role="user", content=clean_message),
        ]

        tool_calls: list[ToolInvocation] = []
        used_safety_tool = False
        iterations = max_iterations if max_iterations is not None else self._settings.max_tool_iterations
        chat_kwargs = {"max_tokens": max_tokens} if max_tokens is not None else {}

        for _ in range(iterations):
            try:
                raw_reply = self._llm.chat(messages, **chat_kwargs)
            except LLMError as exc:
                logger.error("llm_call_failed", error=str(exc))
                return AgentResult(
                    reply="I'm having trouble reaching the language model right now. Please try again shortly.",
                    tool_calls=tool_calls,
                )

            parsed_call = _parse_tool_call(raw_reply)
            if parsed_call is None:
                disclaimer = SAFETY_DISCLAIMER if (mentions_safety_topic(clean_message) or used_safety_tool) else None
                return AgentResult(reply=raw_reply.strip(), tool_calls=tool_calls, disclaimer=disclaimer, flagged_injection=flagged)

            name, arguments = parsed_call
            invocation = ToolInvocation(name=name, arguments=arguments)
            is_local = self._local.has(name)
            schema = self._local.get_schema(name) if is_local else self._mcp.get_tool_schema(name)
            if schema is None:
                invocation.error = f"unknown tool '{name}'"
            else:
                try:
                    validate_tool_arguments(schema, arguments)
                    if is_local:
                        invocation.result = self._local.call(name, arguments, session_id=clean_session_id)
                    else:
                        invocation.result = await self._mcp.call_tool(name, arguments)
                        used_safety_tool = used_safety_tool or self._mcp.get_tool_server(name) == "safety"
                except GuardrailViolation as exc:
                    invocation.error = str(exc)
                except Exception as exc:  # noqa: BLE001 - tool execution failure must degrade, not crash the request
                    logger.error("tool_call_failed", tool=name, error=str(exc))
                    invocation.error = "tool temporarily unavailable"

            tool_calls.append(invocation)
            messages.append(ChatMessage(role="assistant", content=raw_reply))
            observation = invocation.result if invocation.result is not None else f"error: {invocation.error}"
            messages.append(ChatMessage(role="user", content=f"Tool result for {name}: {observation}"))

        messages.append(ChatMessage(role="user", content="Give your final answer now as plain text, no tool calls."))
        try:
            final_reply = self._llm.chat(messages, **chat_kwargs)
        except LLMError:
            final_reply = "I gathered some information but couldn't finish reasoning about it. Please rephrase your question."
        disclaimer = SAFETY_DISCLAIMER if (mentions_safety_topic(clean_message) or used_safety_tool) else None
        return AgentResult(reply=final_reply.strip(), tool_calls=tool_calls, disclaimer=disclaimer, flagged_injection=flagged)


def _parse_tool_call(raw_reply: str) -> tuple[str, dict] | None:
    text = raw_reply.strip()
    if not text.startswith("{"):
        return None
    try:
        # raw_decode parses one JSON value from the start and ignores
        # anything after it — models sometimes emit multiple tool-call
        # objects back to back; json.loads would reject that outright and
        # the whole reply would fall through as an unparsed "final answer".
        # Taking just the first call here is safe: the loop gives the model
        # another turn to make the next call once this one's result is fed back.
        payload, _ = json.JSONDecoder().raw_decode(text)
    except json.JSONDecodeError:
        return None
    if not isinstance(payload, dict):
        return None
    call = payload.get("tool_call")
    if not isinstance(call, dict):
        return None
    name = call.get("name")
    arguments = call.get("arguments", {})
    if not isinstance(name, str) or not isinstance(arguments, dict):
        return None
    return name, arguments
